apiVersion: skaffold/v3
kind: Config
<<<<<<< HEAD
deploy:
 kubectl:
  manifests:
     - ./infra/*
=======
>>>>>>> 78355af4cc1dd2379277071fab886db01dfe6c8b
build:
 artifacts:
  - image: raziiik/meta-user-service
    context: ./User-Service
    sync:
     manual:
     - src: ./src/**/*.ts
       dest: .
    docker:
      dockerfile: Dockerfile
  - image: raziiik/meta-auth-service
    context: ./Auth-Service
    sync:
     manual:
     - src: ./src/**/*.ts
       dest: .
    docker:
      dockerfile: Dockerfile
 local:
  push: false
manifests:
 rawYaml:
 - ./infra/*
deploy:
 kubectl: {}