apiVersion: skaffold/v3
kind: Config
build:
 artifacts:
  - image: raziiik/meta-user-service:latest
    context: ./User-Service
    sync:
     manual:
     - src: ./src/**/*.ts
       dest: .
    docker:
      dockerfile: Dockerfile
  - image: raziiik/meta-auth-service:latest
    context: ./Auth-Service
    sync:
     manual:
     - src: ./src/**/*.ts
       dest: .
    docker:
      dockerfile: Dockerfile
  - image: raziiik/meta-post-service:latest
    context: ./PostService
    sync:
     manual:
     - src: ./src/**/*.ts
       dest: .
    docker:
      dockerfile: Dockerfile
  - image: raziiik/meta-chat-service:latest
    context: ./ChatService
    sync:
     manual:
     - src: ./src/**/*.ts
       dest: .
    docker:
      dockerfile: Dockerfile
  - image: raziiik/meta-story-service:latest
    context: ./StoryService
    sync:
     manual:
     - src: ./src/**/*.ts
       dest: .
    docker:
      dockerfile: Dockerfile
  - image: raziiik/meta-client-service:latest
    context: ./MetaMedia_Frontend
    sync:
     manual:
     - src: ./src/**/*.tsx
       dest: .
     - src: ./MetaMedia_Frontend/*
       dest: .
    docker:
      dockerfile: Dockerfile
  
 local:
  push: false
manifests:
 rawYaml:
 - ./infra/*
deploy:
 kubectl: {}