apiVersion: skaffold/v3
kind: Config

deploy:
 kubectl:
     manifests:
     - ./infra/*

build:
 artifacts:
  - image: raziiik/meta-user-service
    context: ./User-Service
    sync:
     manual:
     - src: ./src/**/*.ts
       dest: .
    docker:
      dockerfile: Dockerfile
  - image: raziiik/meta-auth-service
    context: ./Auth-Service
    sync:
     manual:
     - src: ./src/**/*.ts
       dest: .
    docker:
      dockerfile: Dockerfile
 local:
  push: false
manifests:
 rawYaml:
 - ./infra/*
 deploy:
 kubectl: {}