
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
spec:
  ingressClassName: nginx
  rules:
    - host: metamedia.com
      http:
        paths:
         
          - path: /api/user/?(.*)
            pathType: Prefix
            backend:
              service:
                name: user-srv
                port:
                  number: 3000
          - path: /api/auth/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 3001
          - path: /api/post/?(.*)
            pathType: Prefix
            backend:
              service:
                name: post-srv
                port:
                  number: 3002
          - path: /api/story/?(.*)
            pathType: Prefix
            backend:
              service:
                name: story-srv
                port: 
                  number: 3003
          - path: /api/highlight/?(.*)
            pathType: Prefix
            backend:
              service:
                name: story-srv
                port: 
                  number: 3003
          - path: /api/chat/?(.*)
            pathType: Prefix
            backend:
              service:
                name: chat-srv
                port: 
                  number: 3005
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: client-srv
                port:
                  number: 5173